### PR TITLE
chore: added node 21

### PR DESCRIPTION
**Pull request by jeluard**
Added node21 to build

### CODE REVIEW

**Review by matthewkeil — APPROVED** [review]
Nice!  LGTM!!!  🚀

**Review by matthewkeil — CHANGES_REQUESTED** [review]
shoot!  I just noticed one of the spec test fails... hmmm

**Comment by jeluard** [comment]
Right, I've seen it already in the past. It's sporadic. Need to dig that one.

**Comment by matthewkeil** [comment]
I know that's a specific edge case that I had to add code to the rebuild to cover. I don't remember seeing it manually handled before and remember thinking it was weird that it seemed to pass before. I wonder why it fails all the sudden in 21. Very weird

**Comment by jeluard** [comment]
I've seen it failing before `21`, at least on `macOS`.

**Comment by matthewkeil** [comment]
Closing. Updated bindings test against 21 now

**Pull request closed without merging**
