### PR TITLE
chore: add node v20 support

### PR DESCRIPTION
**Pull request by wemeetagain**

### CODE REVIEW

**Comment by dapplion** [comment]
Some CI for v20 is broken


Main / build-arm (20) (pull_request)
Main / build (ubuntu-20.04, 20) (push)

**Comment by wemeetagain** [comment]
Seems it is flaky. Rerunning fixes it

**Comment by dapplion** [comment]
Tho why is arm arch so flaky too? On master everything is green

**Comment by dapplion** [comment]
arm v20 is failing, I would drop support for it in this PR to unlock other archs and debug latter

**Comment by wemeetagain** [comment]
its also failing in non-arm ubuntu ???

frustratingly, its not failing locally
and seeing the error, its hard to see how it could go so wrong... https://github.com/ChainSafe/blst-ts/actions/runs/5147380281/jobs/9286645208?pr=102

it's failing to do string equality?!
https://github.com/ChainSafe/blst-ts/blob/6ff826db02a1c5363d30e67785742b85c9172dea/test/spec/index.test.ts#LL137C16-L137C36

**Comment by wemeetagain** [comment]
Its all passing.... just quite flaky

**Pull request merged**
